version: "3.4"  # optional since v1.27.0

services:
  log-app:
    container_name: log-app
    build: .
    image: core-api:latest
    command: uvicorn main:app --host 0.0.0.0 --port 5008 --access-log 
    restart: always
    ports:
      - "5008:5008"
    volumes:
      - .:/app
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "logs_app:local-dev"

